name: raildelays
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy
  - torchvision
  - pytorch
  - cudatoolkit=10.1
  - scipy
  - tensorflow
  - scikit-learn
  - pandas
  - jupyter
  - dask
  - matplotlib
  - arrow
  - networkx
  - fastparquet
  - python-snappy
  # - jupyter_contrib_nbextensions: manually install for improved notebook interface